INSERT INTO Books (boo_author, boo_title, boo_date, boo_content, boo_type) 

VALUES ('Yuval Noah Harari', 'Homo deus : Une brève histoire de l\'avenir', '2017-09-06', 'Sapiens retraçait l\'histoire de l\'humanité. Homo Deus interroge son avenir. Que deviendront nos démocraties quand Google et Facebook connaîtront nos goûts et nos préférences politiques mieux que nous-mêmes ? Qu\'adviendra-t-il de l\'Etat providence lorsque nous, les humains, serons évincés du marché de l\'emploi par des ordinateurs plus performants ? Quelle utilisation certaines religions feront-elles de la manipulation génétique ? Homo Deus nous dévoile ce que sera le monde d\'aujourd\'hui lorsque, à nos mythes collectifs tels que les dieux, l\'argent, l\'égalité et la liberté, s\'allieront de nouvelles technologies démiurgiques. Et que les algorithmes, de plus en plus intelligents, pourront se passer de notre pouvoir de décision. Car, tandis que l\'Homo Sapiens devient un Homo Deus, nous nous forgeons un nouveau destin. Best-seller international – plus de 200 000 exemplaires vendus en France, traduit dans près de 40 langues – Sapiens interrogeait l\'histoire de l\'humanité, de l\'âge de la pierre à l\'ère de la Silicon Valley. Le nouveau livre de Yuval Noah Harari offre un aperçu vertigineux des rêves et des cauchemars qui façonneront le XXIe siècle.', 'Histoire');

INSERT INTO Books (boo_author, boo_title, boo_date, boo_content, boo_type) 
values ('Grand Corps Malade','Patients','2017-01-16','Grand Corps Malade, de son vrai nom Fabien Marsaud, est né en 1977, sous le soleil de la Seine-Saint-Denis. Enfant, il veut devenir prof de sport. Mais la vie lui réserve un autre destin. Armé d\'une béquille et d\'un stylo, il se lance dans la musique : en 2006, son premier album, Midi 20, se vend à plus de 600 000 exemplaires et l\'artiste est primé deux fois aux Victoires de la musique.','Histoire');

insert into Books (boo_author, boo_title, boo_date, boo_content, boo_type) 

values('Aldous Huxley','Le meilleur des mondes','2017-08-17','Voici près d\'un siècle, dans d\'étourdissantes visions, Aldous Huxley imagine une civilisation future jusque dans ses rouages les plus surprenants : un Etat Mondial, parfaitement hiérarchisé, a cantonné les derniers humains "sauvages" dans des réserves. La culture in vitro des foetus a engendré le règne des "Alphas ", génétiquement déterminés à être l\'élite dirigeante. Les castes inférieures, elles, sont conditionnées pour se satisfaire pleinement de leur sort. Dans cette société où le bonheur est loi, famille, monogamie, sentiments sont bannis. Le meilleur des mondes est possible. Aujourd\'hui, il nous paraît même familier...','Science-Fiction');